# Generated by Django 3.0.4 on 2020-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200328_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
