# Generated by Django 3.0.4 on 2020-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadesc',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='metatitle',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
