# Generated by Django 3.0.4 on 2020-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200401_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='metadesc',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='metatitle',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='metadesc',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='metatitle',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
