# Generated by Django 3.0.4 on 2020-04-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200401_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='author',
            name='metatitle',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metatitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='metatitle',
        ),
    ]
