# Generated by Django 3.0.4 on 2020-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200408_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='post',
            name='metadesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='metatitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
